export default [
  {
    id: 0,
    label: "常见问题",
    type: "00",
    icon: "1.png",
    expand: false,
    lis: [
      { id: 0, label: "账号及安全", active: true },
      { id: 1, label: "充/提币", active: false },
      { id: 2, label: "买/卖数字资产", active: false },
      { id: 3, label: "各种交易", active: false },
      { id: 4, label: "邀请好友及节点代理", active: false },
      { id: 5, label: "金融业务", active: false },
      { id: 6, label: "其他内容", active: false },
    ],
  },
  {
    id: 1,
    label: "新手教程",
    type: "10",
    icon: "2.png",
    expand: false,
    lis: [
      { id: 0, label: "如何注册账号" },
      { id: 1, label: "充/提币" },
      { id: 2, label: "买/卖数字资产" },
      { id: 3, label: "现货交易" },
      { id: 4, label: "合约交易" },
      { id: 5, label: "跟单交易" },
      { id: 6, label: "金融业务" },
      { id: 7, label: "其他" },
    ],
  },
  {
    id: 2,
    label: "产品说明",
    type: "20",
    icon: "3.png",
    expand: false,
    lis: [
      { id: 0, label: "交易规则",},
      { id: 1, label: "风控规则", },
      { id: 2, label: "C2C交易",  },
      { id: 3, label: "现货交易",  },
      { id: 4, label: "合约交易",  },
      { id: 5, label: "跟单交易",  },
    ],
  },
];
