// '1', '3', '5', '15', '30', '60', '120', '240', '360', '480', '720', '1D', '3D', '1W','1M'
export default [
    {
        label: "lang_888",
        resolution: "1MIN",
        interval: '1',
        chartType: 3,
        websockSend: "1MIN",
        value: 0,
        active: true,
    },
    {
        label: "lang_803",
        resolution: "1MIN",
        interval: '1',
        chartType: 1,
        websockSend: "1MIN",
        value: 1,
        active: true,
    },
    {
        label: "lang_815",
        resolution: "5MIN",
        interval: '5',
        chartType: 1,
        websockSend: "5MIN",
        value: 3,
        active: true,
    },
    {
        label: "lang_802",
        resolution: "15MIN",
        interval: '15',
        chartType: 1,
        websockSend: "15MIN",
        value: 4,
        active: true,
    },
    {
        label: "lang_812",
        resolution: "30MIN",
        interval: '30',
        chartType: 1,
        websockSend: "30MIN",
        value: 5,
        active: true,
    },
    {
        label: "lang_805",
        resolution: "60MIN",
        interval: '60',
        chartType: 1,
        websockSend: "60MIN",
        value: 6,
        active: false,
    },
    {
        label: "lang_814",
        resolution: "4H",
        interval: '240',
        chartType: 1,
        websockSend: "4H",
        value: 8,
        active: false,
    },
    {
        label: "lang_804",
        resolution: "1DAY",
        interval: '1D',
        chartType: 1,
        websockSend: "1DAY",
        value: 12,
        active: false,
    },
    // {
    //     label: "3日",
    //     resolution: "3d",
    //     chartType: 1,
    //     websockSend: "3d",
    //     value: 13,
    //     active: false,
    // },

    {
        label: "lang_1086",
        resolution: "1WEEK",
        interval: '1W',
        chartType: 1,
        websockSend: "1WEEK",
        value: 13,
        active: false,
    },
    {
        label: "lang_1064",
        resolution: "1MON",
        interval: '1M',
        chartType: 1,
        websockSend: "1MON",
        value: 14,
        active: false,
    },
]