export const rulesLabel = [
  { id: 1, label: "rules.名称", prop: "symbolCode", width: "110" },
  {
    id: 2,
    label: "rules.合约类型",
    prop: "marketType",
    hover: false,
    tip: "",
    width: "150",
  },
  {
    id: 3,
    label: "rules.保证金币种",
    prop: "quoteAssetCode",
    hover: false,
    tip: "",
    width: "90",
  },
  {
    id: 4,
    label: "rules.价格乘数",
    prop: "priceDecimal",
    hover: false,
    tip: "",
    width: "120",
  },
  {
    id: 5,
    label: "rules.数量乘数",
    prop: "qtyDecimal",
    hover: false,
    tip: "",
    width: "80",
  },
  {
    id: 6,
    label: "rules.最小委托量",
    prop: "singleMinQty",
    hover: false,
    tip: "",
    width: "110",
  },
  {
    id: 7,
    label: "rules.最大委托量",
    prop: "singleMaxQty",
    hover: false,
    tip: "",
    width: "110",
  },
  {
    id: 8,
    label: "rules.最小委托量(USDT)",
    prop: "singleMinQuoteQty",
    hover: false,
    tip: "",
    width: "120",
  },
  {
    id: 9,
    label: "rules.最大委托量(USDT)",
    prop: "singleMaxQuoteQty",
    hover: false,
    tip: "",
    width: "120",
  },
  {
    id: 10,
    label: "rules.最大杠杆倍数",
    prop: "maxLever",
    hover: false,
    tip: "",
    width: "100",
  },
  {
    id: 11,
    label: "rules.下次结算资金费率",
    prop: "fundingRate",
    hover: false,
    tip: "",
    width: "120",
  },
  {
    id: 12,
    label: "rules.资金费率结算周期",
    prop: "fundingRateSettlementCycle",
    hover: false,
    tip: "",
    width: "150",
  },
  {
    id: 13,
    label: "rules.指数来源",
    prop: "dataSources",
    hover: false,
    tip: "",
    width: "180",
  },
  {
    id: 14,
    label: "rules.合约面值",
    prop: "faceValue",
    hover: false,
    tip: "",
    width: "80",
  },
  {
    id: 15,
    label: "rules.张数定义",
    prop: "definition",
    hover: false,
    tip: "",
    width: "110",
  },
];
export const leverageLabel = [
  { id: 1, label: "rules.层级", prop: "index", width: 80 },
  {
    id: 2,
    label: "rules.交易对名称",
    prop: "coinMarket",
    hover: false,
    tip: "包含您的多空仓位总和。",
    width: 100,
  },
  {
    id: 3,
    label: "rules.档位",
    prop: "gear",
    hover: false,
    tip: "包含您的多空仓位总和。",
    width: 80,
  },
  {
    id: 4,
    label: "rules.最小张数",
    prop: "minPositionAmount",
    hover: false,
    tip: "包含您的多空仓位总和。",
    width: 100,
  },
  {
    id: 5,
    label: "rules.最大张数",
    prop: "maxPositionAmount",
    hover: false,
    tip: "包含您的多空仓位总和。",
    width: 100,
  },
  {
    id: 6,
    label: "rules.最大杠杆倍数",
    prop: "maximumLeverage",
    hover: false,
    tip: "持仓价值级距下可使用的最高杠杆倍数。",
    width: 100,
  },
  {
    id: 7,
    label: "rules.维持保证金比率",
    prop: "maintenanceMarginRatio",
    hover: false,
    tip: "维持保证金是根据您的持仓价值级距所对应的维持保证金率计算而来。",
    width: 120,
  },
];
